name: Continuous Integration

on: [push]

jobs:
  ci:
#    if: ${{ false }}
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update
        run: sudo apt-get update
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: sbt mill
      - name: Setup Dependencies
        run: sudo apt-get install -y ccache
      - name: Initialize submodule
        run: git submodule update --init --recursive
      - name: Install Verilator 5.044
        run: |
          sudo apt-get install -y git help2man perl python3 make g++ libfl2 libfl-dev zlib1g zlib1g-dev
          git clone https://github.com/verilator/verilator
          cd verilator
          git checkout v5.044
          autoconf
         ./configure
         make -j$(nproc)
         sudo make install
      - name: Show versions
        run: |
          java -version
          sbt --version
      - name: Setup chisel-axi-utils and run tests
        shell: bash
        run: |
          make -C chisel-axi-utils setup
          source chisel-axi-utils/.venv/bin/activate
          sbt test
